# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Community Budget', max_length=60, verbose_name='Budget Title')),
                ('residence_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('neighborhood', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='HOA Division', max_length=60, verbose_name='Neighborhood Title')),
                ('description', models.TextField(default='Description of why and how this expense is needed', verbose_name='Description')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('start_date', models.DateField(verbose_name='Starts on')),
                ('end_date', models.DateField(verbose_name='Ends on')),
                ('type', models.CharField(default='Improvement', max_length=50, verbose_name='Type of Expense')),
                ('approved', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
        ),
    ]
