# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neighborhood', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Community Budget', max_length=60, verbose_name='Budget Title')),
                ('total_funds', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Funds')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Expenses')),
                ('residence_fee', models.DecimalField(decimal_places=2, default=10.0, max_digits=8, verbose_name='Residence Fee')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('types', models.CharField(choices=[('IMP', 'Improvement'), ('REP', 'Repair'), ('REC', 'Recreation'), ('FEE', 'Fee'), ('OTH', 'Other')], default='REP', max_length=3)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Expense', max_length=60, verbose_name='Expense Title')),
                ('description', models.TextField(default='Description of why and how this expense is needed', verbose_name='Description')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('start_date', models.DateTimeField(verbose_name='Starts on')),
                ('end_date', models.DateTimeField(verbose_name='Ends on')),
                ('type', models.CharField(max_length=50, verbose_name='Type of Expense')),
                ('approved', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
        ),
    ]
