# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='types',
            field=models.CharField(choices=[('IMP', 'Improvement'), ('REP', 'Repair'), ('REC', 'Recreation'), ('FEE', 'Fee'), ('OTH', 'Other')], default='REP', max_length=3),
        ),
    ]
