# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Expenses'),
        ),
        migrations.AddField(
            model_name='budget',
            name='total_funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Funds'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='budget',
            name='neighborhood',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood', verbose_name='Neighborhood'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='residence_fee',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Residence Fee'),
        ),
    ]
