# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
