# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20160128_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='end_date',
            field=models.DateTimeField(verbose_name='Ends on'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='start_date',
            field=models.DateTimeField(verbose_name='Starts on'),
        ),
    ]
