# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20160126_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='neighborhood_id',
            field=models.IntegerField(default=-1),
        ),
    ]
