# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20160128_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(default='Expense', max_length=60, verbose_name='Expense Title'),
        ),
    ]
