# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20160126_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='types',
            field=models.CharField(choices=[('IMP', 'Freshman'), ('REP', 'Sophomore'), ('REC', 'Junior'), ('FEE', 'Senior'), ('OTH', 'Senior')], default='REP', max_length=3),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Type of Expense'),
        ),
    ]
