# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20160128_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
