# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_expense_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='approval_date',
            field=models.DateTimeField(null=True),
        ),
    ]
