# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='family_name',
            field=models.CharField(default='family_name', max_length=50),
        ),
    ]
