# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0001_initial'),
        ('accounts', '0002_boardmemberprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmemberprofile',
            name='neighborhood_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood'),
        ),
    ]
