# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-25 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_boardmemberprofile_neighborhood_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardmemberprofile',
            name='house',
        ),
        migrations.RemoveField(
            model_name='boardmemberprofile',
            name='neighborhood_id',
        ),
        migrations.RemoveField(
            model_name='boardmemberprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='Default biography', max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='member_status',
            field=models.CharField(default='neighbor', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='neighborhood_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='BoardMemberProfile',
        ),
    ]
