# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160325_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.House'),
        ),
    ]
