# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='assoc_obj_id',
            field=models.IntegerField(default=-1),
        ),
    ]
