# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
