# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default='Default question description', max_length=500),
        ),
    ]
