# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0001_initial'),
        ('polls', '0002_auto_20160129_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
