# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_yes_no',
            field=models.BooleanField(default=False),
        ),
    ]
