# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_poll_votepoll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='status',
            field=models.CharField(default='TBD', max_length=20),
        ),
    ]
