# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-25 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20160325_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='recipients',
            field=models.ManyToManyField(related_name='recipients', to=settings.AUTH_USER_MODEL),
        ),
    ]
