# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20160325_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='last_message_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
