# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0004_auto_20160316_0152'),
        ('polls', '0001_initial'),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='marker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='markers.Marker'),
        ),
        migrations.AddField(
            model_name='feedpost',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
