# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-25 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20160324_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='title',
            field=models.CharField(default='Feed Post Title', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedpost',
            name='type',
            field=models.CharField(default='ANNOUNCEMENT', max_length=50),
        ),
    ]
