# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20160325_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
