# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_view'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='PostView',
        ),
    ]
