# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_auto_20160410_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedpost',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='feedpost',
            name='title',
        ),
    ]
