# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20160412_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
    ]
