# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_auto_20160417_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpost',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
