# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='marker_type',
            field=models.CharField(choices=[('HOU', 'House'), ('EVE', 'Event'), ('TRA', 'Trash'), ('CON', 'Construction'), ('THF', 'Theft'), ('YAR', 'Yard Sale'), ('POL', 'Pool'), ('SPA', 'Spa')], default='EVE', max_length=3),
        ),
    ]
