# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_auto_20160316_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='marker_type',
        ),
        migrations.AddField(
            model_name='marker',
            name='type',
            field=models.CharField(default='DEFAULT', max_length=40),
        ),
    ]
