# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0003_auto_20160316_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='type',
            new_name='type_of_marker',
        ),
    ]
