# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0004_auto_20160316_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
