# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0005_auto_20160324_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='marker',
            name='description',
            field=models.TextField(default='Default marker description.', max_length=300),
        ),
    ]
