# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0006_auto_20160327_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marker',
            old_name='name',
            new_name='title',
        ),
    ]
