# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 17:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markers', '0007_auto_20160327_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
