# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Comment Text')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator_id', models.IntegerField(verbose_name='Creator ID')),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Discussion Title', max_length=250, verbose_name='Discussion Title')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator_id', models.IntegerField(verbose_name='Creator ID')),
                ('neighborhood_id', models.IntegerField(verbose_name='Neighborhood_id')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discussions.Discussion', unique=True),
        ),
    ]
