# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_auto_20160129_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
