# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('residence_fee', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('division_title', models.CharField(default='HOA Division', max_length=60)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
