# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('division_title', models.CharField(default='HOA Division', max_length=60)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('budget_id', models.IntegerField(default=-1)),
            ],
        ),
    ]
