# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='lat',
            field=models.FloatField(default=-119.055079),
        ),
        migrations.AddField(
            model_name='house',
            name='lon',
            field=models.FloatField(default=34.220912),
        ),
    ]
