# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 04:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markers', '0007_auto_20160327_2359'),
        ('neighborhood', '0002_auto_20160328_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(default='Event Location', max_length=100)),
                ('title', models.CharField(default='Event Title', max_length=200)),
                ('type', models.CharField(default='Community', max_length=50)),
                ('description', models.TextField(default='Event Description.', max_length=1000)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='markers.Marker')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood')),
            ],
        ),
    ]
