# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(default='COMMUNITY', max_length=50),
        ),
    ]
